### ISSUE TITLE
[ED] Hover/focus on div for radio/checkbox elements larger than clickable area (label)

### ISSUE THREAD

**Issue by iamjolly** [w3c/wai-statements#75]
The `div` that wraps the radio/checkbox element and its label has a focus and hover state change that makes it seem like it's a larger clickable area than the label text itself.

This could be confusing for some users. If possible, consider making the entire `div` clickable to toggle the state of the input.

Screenshot showing the wide area highlighted on hover/focus, but only the smaller text of the label is actually clickable:

<img width="978" alt="visible hover/focus for labels which is much larger than the clickable/active area" src="https://user-images.githubusercontent.com/1093423/48527949-1ad21680-e84a-11e8-9c6a-c62a2bba19eb.png">

**Comment by rvantonisse** [comment]
@yatil This has to do with the wai website theme styling inside `form-elements.css`. 
A fix for this could be to set default width of the label to 100% and make sure the label will shrink like this:
```css
/* radio-field is a flex container need to define width to tackle flexbugs */
.radio-field label
{
  display: block;
  width: 100%;
  flex-shrink: 1;
}
```
Mind though styling flex can still get icky supporting IE and EDGE.

I need to make sure all radio-field labels dont have extra siblings other than input inside generator.html
